app/therapist/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email

from app.errors.form_error_msg import FormErrorMsg


class AddClientForm(FlaskForm):
    email = StringField('Email, pod kterým se klient registroval',
                        validators=[DataRequired(message=FormErrorMsg.Email.Required),
                                    Email(message=FormErrorMsg.Email.Invalid)])
    submit = SubmitField('Přidat klienta')

app/therapist/__init__.py
"""This module provides functionality for therapists."""

from flask import Blueprint

bp = Blueprint('therapist', __name__)

from app.therapist import forms, routes

app/therapist/routes.py
from flask import flash, Markup, redirect, render_template, url_for
from flask_login import current_user

from app import common, db, limiter
from app.account.role import Role, role_required
from app.account.utils import logged_user_limiter
from app.therapist import bp
from app.therapist.emails import send_alliance_end_email, send_alliance_offer_email
from app.therapist.forms import AddClientForm
from app.models import Test, ThoughtRecord, User
from app.tests.cesd_r import CESD_R
from app.tests import graphs as test_graphs
from config import Config


@bp.route('client/<public_id>/thought-record-browse/')
@role_required(Role.Therapist)
def thought_record_browse(public_id):
    client = User.query.filter_by(public_id=public_id).first_or_404()
    return common.routes.thought_record_browse(client, 'therapist.thought_record_browse',
                                               public_id=public_id)


@bp.route('/list-of-clients')
@role_required(Role.Therapist)
def list_of_clients():  # TODO: cells with links to clients' lists of tests and TRecords could show timestamp of last test/TRecord written
    return render_template('therapist/list_of_clients.html', user=current_user, clients=current_user.clients.all())


@bp.route('/add-client', methods=['GET', 'POST'])
@limiter.limit(Config.ADD_CLIENT_VIEW_LIMIT, key_func=logged_user_limiter, methods=['POST'])
@role_required(Role.Therapist)
def add_client():
    form = AddClientForm()
    if form.validate_on_submit():
        form_email = form.email.data.lower()
        if current_user.email == form_email:
            flash("Nelze sledovat sebe sama.")
            return redirect(url_for('therapist.add_client'))
        client = User.query.filter(User.email == form_email) \
                           .filter(User.role == Role.Client).first()
        if client:
            if client.is_in_alliance(current_user):
                flash(Markup(f"Klient na emailu {form_email} je s Vámi již propojen. <br><br> \
                               Klienta lze nalézt vyhledáním dle emailu v tabulce níže nebo na \
                               <a href='{url_for('therapist.client_overview', public_id=client.public_id)}'> \
                               tomto odkazu</a>."))
                return redirect(url_for('therapist.list_of_clients'))
            send_alliance_offer_email(client, current_user)
        flash(f"Zpracováváme Vaši žádost o propojení s klientem na emailu: {form_email}. \
                Nachází-li se v naší databázi, bude mu odeslána pozvánka. O jejím přijetí budete notifikováni \
                emailem.")
        return redirect(url_for('therapist.list_of_clients'))
    return render_template('therapist/add_client.html', user=current_user, form=form)


@bp.route('/remove-client/<public_id>')
@role_required(Role.Therapist)
def remove_client(public_id):
    client = User.query.filter_by(public_id=public_id).first_or_404()
    if current_user.is_in_alliance(client):
        current_user.break_alliance(client)
        db.session.commit()
        send_alliance_end_email(client, current_user)
        flash(f"Uživatel {client.email} odebrán.")
    return redirect(url_for('therapist.list_of_clients'))


@bp.route('/client/<public_id>')
@role_required(Role.Therapist)
def client_overview(public_id):
    client = User.query.filter_by(public_id=public_id).first_or_404()
    tests = client.tests.filter_by(test=CESD_R.label).order_by(Test.timestamp.desc()).all()
    thought_records = client.thought_records.order_by(ThoughtRecord.timestamp.desc()).all()
    graphs = [test_graphs.line(CESD_R.label, tests)] if tests else None
    return render_template('therapist/client_overview.html', client=client, thought_records=thought_records,
                           tests=tests, graphs=graphs)


@bp.route('/client/<public_id>/test-browse')
@role_required(Role.Therapist)
def test_browse(public_id):
    client = User.query.filter_by(public_id=public_id).first_or_404()
    tests = client.tests.order_by(Test.timestamp.desc()).all()
    return render_template('therapist/test_browse.html', client=client, tests=tests)


@bp.route('/manual')
@role_required(Role.Therapist)
def manual():
    return render_template('therapist/manual.html', title='Návod k užívání PAT')

app/templates/therapist/_therapist_view_base.html
{% extends "core/base.html" %}
{% from "core/macros.html" import highlight_active_pill %}

{% block app_content %}
<h1>Klient:
    <a href="{{ url_for('therapist.client_overview', public_id=client.public_id) }}">
        {{ client.username }}</a>
</h1>
<ul class="nav nav-pills">
    <li class="nav-item">
        {% set overview_url = url_for('therapist.client_overview', public_id=client.public_id) %}
        <a class="nav-link {{ highlight_active_pill(overview_url) }}" href="{{ overview_url }}">
            Celkový přehled</a>
    </li>
    <li class="nav-item">
        {% set thought_records_url = url_for('therapist.thought_record_browse', public_id=client.public_id) %}
        <a class="nav-link {{ highlight_active_pill(thought_records_url) }}" href="{{ thought_records_url }}">
            Záznamy myšlenek</a>
    </li>
    <li class="nav-item">
        {% set tests_url = url_for('therapist.test_browse', public_id=client.public_id) %}
        <a class="nav-link {{ highlight_active_pill(tests_url) }}" href="{{ tests_url }}">
            Vyplněné dotazníky</a>
    </li>
</ul>

{% block client_content %}
{% endblock client_content %}

{% endblock app_content %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/therapist/add_client.html
{% extends "core/base.html" %}
{% from "bootstrap/form.html" import render_form as render_wtform %}

{% block app_content %}
    <h1>Přidat klienta do terapeutického vztahu</h1>
    <p>
        Pro přidání klienta je potřeba, aby již měl vytvořený klientský účet v PAT.
        V takovém případě po přidání obdrží na email pozvánku do terapeutického vztahu.
        Po jejím přijetí budete propojeni.
    </p>
    <div class="row">
        <div class="col-md-4">
            {{ render_wtform(form) }}
        </div>
    </div>
{% endblock %}

app/templates/therapist/client_overview.html
{% extends "therapist/_therapist_view_base.html" %}
{% from "core/macros.html" import init_graph_magic, init_table_magic %}

{% block client_content %}
    <h2 class="mt-2">Graf vývoje</h2>
    {% if graphs %}
        {% for graph in graphs %}
            <div id="{{ graph['id'] }}"></div>
        {% endfor %}
    {% else %}
        <p>Zde bude k dispozici graf vývoje klienta na základě vyplněných testů.</p>
    {% endif %}
    <h2><a href="{{ url_for('therapist.test_browse', public_id=client.public_id) }}">
        Dotazníky</a></h2>
    {% if tests %}
        {% include "common/_test_history.html" %}
    {% else %}
        <p>Zde budou k dispozici výsledky vyplněných testů klienta, jakmile nějaké vyplní.</p>
    {% endif %}
    <h2 class="mt-4"><a href="{{ url_for('therapist.thought_record_browse', public_id=client.public_id) }}">
        Záznamy myšlenek</a></h2>
    {% if thought_records %}
        {% include "common/_thought_record_history.html" %}
    {% else %}
        <p>Zde budou k dispozici vyplněné záznamy myšlenek klienta, jakmile nějaké zapíše.</p>
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ init_table_magic(table_id="thought_records",
                        columns=[ {'type': 'moment-timestamp'}, None, None, None, None, None ],
                        order=[[0, 'desc' ]],
                        paging_type="full_numbers") }}
    {{ init_table_magic(table_id="tests",
                        columns=[ {'type': 'moment-timestamp'}, None, None ],
                        order=[[0, 'desc' ]],
                        paging_type="full_numbers") }}
    {{ init_graph_magic(graphs=graphs) }}
{% endblock %}

app/templates/therapist/list_of_clients.html
{% extends "core/base.html" %}
{% from "core/macros.html" import init_modal_magic, init_table_magic %}

{% block app_content %}
    <h1>Terapeut: {{ user.username }}</h1>
    <hr>
    <h2>Propojení klienti</h2>
    {% if clients %}
        <table class="table table-hover" id="clients">
            <thead>
                <tr valign="top">
                    <th>Uživatelské jméno</th>
                    <th>Email</th>
                    <th>Graf vývoje</th>
                    <th>Seznam dotazníků</th>
                    <th>Seznam záznamů myšlenek</th>
                    <th>Odpojit klienta</th>
                </tr>
            </thead>
            <tbody>
                {% for client in clients %}
                    <tr>
                        <td><a href="{{ url_for('therapist.client_overview', public_id=client.public_id) }}">
                            {{ client.username }}</a></td>
                        <td><a href="{{ url_for('therapist.client_overview', public_id=client.public_id) }}">
                            {{ client.email }}</a></td>
                        <td><a href="{{ url_for('therapist.client_overview', public_id=client.public_id) }}">
                            Graf</a></td>
                        <td><a href="{{ url_for('therapist.test_browse', public_id=client.public_id) }}">
                            Dotazníky</a></td>
                        <td><a href="{{ url_for('therapist.thought_record_browse',
                                                 public_id=client.public_id) }}">
                            Záznamy</a></td>
                        <td><button class="btn btn-link btn-anchor p-0 border-0 align-baseline" type="button"
                                    data-toggle="modal" data-target="{{ '#confirm_delete' + client.public_id }}">
                            Odpojit klienta
                        </button></td>
                            {% call init_modal_magic(id="confirm_delete" + client.public_id,
                                                     title="Zrušení terapeutického vztahu",
                                                     close_label="Zpět", confirm_label="Potvrdit ukončení vztahu",
                                                     confirm_href=url_for('therapist.remove_client',
                                                                          public_id=client.public_id) ) %}
                                <p>
                                    Pokračováním zrušíte propojení Vašeho účtu s klientem {{ client.username }}.
                                    Jeho/její data se tak pro Vás stanou nepřístupnými.
                                </p>
                                <p>
                                    Klient o ukončení propojení obdrží upozornění.
                                </p>
                                <p>
                                    Tento krok by měl být proveden pouze po jeho konzultaci s klientem.
                                </p>
                                <p>
                                    Přejete si pokračovat?
                                </p>
                            {% endcall %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <p>Zde bude k dispozici seznam Vašich klientů.</p>
    <p>Chcete-li začít spolupráci s prvním klientem,
        <a href="{{ url_for('therapist.add_client') }}">
            klikněte na tento odkaz.
        </a>
    </p>
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ init_table_magic(table_id="clients",
                        columns=[ None,
                                  None,
                                  {'orderable': false},
                                  {'orderable': false},
                                  {'orderable': false},
                                  {'orderable': false}, ],
                        order=[[0, 'asc' ]],
                        info=False,
                        page_length=50,
                        paging_type="simple_numbers") }}
{% endblock %}

app/templates/therapist/manual.html
{% extends "core/base.html" %}

{% block app_content %}
<h1>
    Návod k užívání PAT
</h1>
<ul class="nav nav-tabs" id="infoTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="client_detail-tab" data-toggle="tab" href="#client_detail"
           role="tab" aria-controls="client detail" aria-selected="true">
           Detail klienta
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="thought_records-tab" data-toggle="tab" href="#thought_records"
           role="tab" aria-controls="thought records" aria-selected="false">
            Záznamy automatických myšlenek
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tests-tab" data-toggle="tab" href="#tests"
           role="tab" aria-controls="tests" aria-selected="false">
            Dotazníky
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="therapeutic_alliance-tab" data-toggle="tab" href="#therapeutic_alliance"
           role="tab" aria-controls="therapeutic alliance" aria-selected="false">
            Terapeutická aliance
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="edit_profile-tab" data-toggle="tab" href="#edit_profile"
           role="tab" aria-controls="edit_profile" aria-selected="false">
            Úprava účtu
        </a>
    </li>
</ul>
<div class="tab-content" id="infoTabContent">
    <div class="tab-pane fade show active responsive-tab" id="client_detail" role="tabpanel" aria-labelledby="client_detail-tab">
        <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="client_detail">
                <a href="#collapse-client_detail" data-toggle="collapse">
                    <h5 class="mb-0">
                        Detail klienta
                    </h5>
                </a>
        </div>
        <div id="collapse-client_detail" class="collapse" role="tabpanel">
            <h3>
                Umístění
            </h3>
            <p>
                V sekci <a href="{{ url_for('therapist.list_of_clients') }}">Seznam klientů</a>. Kliknutím
                na jméno či email klienta se zobrazí jeho detail.
            </p>
            <h3>
                Obsah a ovládání
            </h3>
            <p>
                Momentálně je v přehledu dostupný graf vývoje stavu klienta, výsledky testů
                a záznamy automatických myšlenek.
            </p>
            <p>
                Ovládání těchto prvků je blíže popsáno v jejich odpovídajících záložkách na této stránce.
            </p>
        </div>
    </div>
    <div class="tab-pane fade responsive-tab" id="thought_records" role="tabpanel" aria-labelledby="thought_records-tab">
        <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="thought_records">
                <a href="#collapse-thought_records" data-toggle="collapse">
                    <h5 class="mb-0">
                        Záznamy automatických myšlenek
                    </h5>
                </a>
        </div>
        <div id="collapse-thought_records" class="collapse" role="tabpanel">
            <h3>
                Umístění
            </h3>
            <p>
                Dostupné v detailu klienta, případně lze prokliknout přímo
                v <a href="{{ url_for('therapist.list_of_clients') }}">Seznamu klientů.</a>
            </p>
            <h3>
                Vyhledávání a třídění záznamů
            </h3>
            <p>
                V přehledu záznamů myšlenek lze vyhledávat užitím pole 'Vyhledat' v pravém horním rohu přehledu.
                Vyhledání není potřeba potvrzovat žádnou klávesou, probíhá v reálném čase během psaní.
                Vyhledávání prochází všechna pole záznamu myšlenky, lze vyhledat i konkrétní datum nebo čas.
                Čas nebo datum je nutno zadat ve stejném formátu jako je v jednotlivých záznamech.
            </p>
            <p>
                Záznamy je možno řadit podle data poklepáním na šipky vedle nadpisu 'Čas'. Výchozí řazení je sestupné
                podle času - nejvýše jsou nové myšlenky.
            </p>
            <p>
                Záznamy lze řadit i dle ostatních polí - toho lze využít pro nalezení nedokončených záznamů. Pokud
                například kliknete na nadpis 'Výsledek', aby se záznamy seřadily vzestupně podle tohoto pole
                (napravo od nadpisu 'Výsledek' bude začerněna šipka směřujíc vzhůru), seřadí se na vrcholu
                přehledu všechny záznamy, jež nemají vyplněno pole 'Výsledek'.
            </p>
            <h3>
                Ze strany klienta
            </h3>
            <p>
                Klient může vytvořit libovolný počet záznamů za den. Záznamy lze libovolně upravovat a mazat.
                Vyhledávání a řazení záznamů má u klientů stejnou funkcionalitu jako máte ve svém zobrazení
                klientových záznamů.
            </p>
        </div>
    </div>
    <div class="tab-pane fade responsive-tab" id="tests" role="tabpanel" aria-labelledby="tests-tab">
        <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="tests">
                <a href="#collapse-tests" data-toggle="collapse">
                    <h5 class="mb-0">
                        Dotazníky
                    </h5>
                </a>
            </div>
        <div id="collapse-tests" class="collapse" role="tabpanel">
            <h3>
                Umístění
            </h3>
            <p>
                Dostupné v detailu klienta, případně lze prokliknout přímo
                v <a href="{{ url_for('therapist.list_of_clients') }}">Seznamu klientů.</a>
            </p>
            <h3>
                Přehled vyplněných testů
            </h3>
            <p>
                V přehledu vyplněných testů je možno vyhledávat a řadit podobně jako v přehledu záznamů myšlenek.
            </p>
            <h3>
                Graf vývoje
            </h3>
            <p>
                Tento graf zobrazuje vývoj hrubého skóru testu v čase.
            </p>
            <p>
                V grafu je možné libovolné úseky přiblížit/oddálit kolečkem myši. Pro návrat do výchozího zobrazení
                lze dvakrát poklepat na graf nebo kliknout na malou ikonku domečku v pravém horním rohu grafu.
            </p>
            <h3>
                Ze strany klienta
            </h3>
            <p>
                Není uvedena žádná doporučená frekvence testů - ponecháno na Vaše zvážení a konzultaci s klientem.
                Počet vyplněných testů není pro klienty nijak omezen. Klienti mohou výsledek vyplněného testu smazat.
            </p>
            <p>
                Graf vývoje a jeho ovládání je u klientů identické s tím, jaké máte na detailu klienta.
            </p>
        </div>
    </div>
    <div class="tab-pane fade responsive-tab" id="therapeutic_alliance" role="tabpanel" aria-labelledby="therapeutic_alliance-tab">
        <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="therapeutic_alliance">
                <a href="#collapse-therapeutic_alliance" data-toggle="collapse">
                    <h5 class="mb-0">
                        Terapeutická aliance
                    </h5>
                </a>
            </div>
        <div id="collapse-therapeutic_alliance" class="collapse" role="tabpanel">
            <h3>
                Terapeutický vztah
            </h3>
            <p>
                Terapeutický vztah zde označuje propojení účtu klienta s účtem terapeuta. Svůj účet můžete propojit
                s libovolným počtem klientů.
            </p>
            <p>
                Též klient může navázat vztah s více terapeuty současně - např. pro případ, že se kombinovaně léčí
                u psychiatra i psychoterapeuta.
            </p>
            <h3>
                Jak vznikne a co znamená
            </h3>
            <p>
                Pro vytvoření tohoto propojení je potřeba, aby klient měl v PAT vytvořený účet. Následně lze z Vašeho
                terapeutického účtu odeslat žádost o propojení prostřednictvím <a href="{{ url_for('therapist.add_client') }}">
                tohoto formuláře</a> (je dostupný i z hlavní nabídky). Klient obdrží email s potvrzovacím odkazem,
                jehož použitím (= navštívením odkazu v internetovém prohlížeči) se vytvoření vztahu potvrdí.
            </p>
            <p>
                Komplikovanost tohoto procesu je primárně dána snahou o vyšší zabezpečení dat klientů. Oproti např.
                sociálním sítím, kde lze účty propojit přímo v aplikaci, zde klient propojením udělí přístup k podstatně
                intimnějším datům. Byl proto zvolen email jako další vrstva zabezpečení - případný útočník
                by k získání citlivých dat musel prolomit nejen účet klienta v PAT, ale i jeho email.
            </p>
            <p>
                Po dobu propojení budete mít přístup ke všem terapeutickým datům klienta - vyplněným záznamům myšlenek,
                výsledkům testů a grafu vývoje. Po dobu propojení klient v PAT uvidí Vaši emailovou adresu.
            </p>
            <h3>
                Ukončení vztahu
            </h3>
            <p>
                Terapeutický vztah můžete ukončit Vy i Váš klient. Pokud byste si přál/-a vztah ukončit,
                lze tak učinit v sekci <a href="{{ url_for('account.edit_profile') }}">Upravit profil.</a>
            </p>
            <p>
                Prosíme o včasnou konzultaci a připravení klientů na tento krok.
            </p>
            <p>
                Pokud by naopak klient ukončil propojení s Vámi, bude Vám odesláno upozornění na email.
            </p>
            <p>
                Dále vztah může zaniknout pokud byste Vy nebo Váš klient dokončil žádost o smazání účtu.
                V takovém případě bude propojení ukončeno a protistrana bude o tomto stavu upozorněna.
            </p>
        </div>
    </div>
    <div class="tab-pane fade responsive-tab" id="edit_profile" role="tabpanel" aria-labelledby="edit_profile-tab">
        <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="edit_profile">
                <a href="#collapse-edit_profile" data-toggle="collapse">
                    <h5 class="mb-0">
                        Úprava účtu
                    </h5>
                </a>
            </div>
        <div id="collapse-edit_profile" class="collapse" role="tabpanel">
            <h3>
                Umístění
            </h3>
            <p>
                Všechny zde uvedené úkony lze provést v sekci
                <a href="{{ url_for('account.edit_profile') }}">Upravit profil.</a>
            </p>
            <h3>
                Uživatelské jméno
            </h3>
            <p>
                Své uživatelské jméno můžete kdykoliv změnit.
                Pod tímto jménem Vás vidí klienti, se kterými jste v terapeutickém vztahu.
            </p>
            <h3>
                Změna hesla
            </h3>
            <p>
                Pro změnu hesla je z bezpečnostních důvodů nutné mít přístup na email, s nímž jste se v PAT
                registroval/-a. Po odeslání žádosti o změnu v sekci
                <a href="{{ url_for('account.edit_profile') }}">Upravit profil</a>
                Vám bude na tento email odeslán potvrzovací odkaz. Ten Vás přesměruje na formulář k vytvoření
                nového hesla.
            </p>
            <h3>
                Smazání účtu
            </h3>
            <p>
                Smazání účtu je nevratná záležitost s okamžitou platností. Po odeslání žádosti Vám na email uvedený
                při registraci přijde potvrzovací odkaz. Použitím tohoto odkazu bude Váš účet a všechna Vaše data
                s ním spojená trvale smazána.
            </p>
            <p>
                Pokud byste si smazání účtu po odeslání žádosti rozmyslel/-a je tak možno pouze před použitím
                potvrzovacího odkazu. V takovém případě doporučujeme email s odkazem z bezpečnostních důvodů smazat.
                Po užití odkazu již obnova účtu není možná.
            </p>
        </div>
    </div>
</div>
{% endblock %}

app/templates/therapist/test_browse.html
{% extends "therapist/_therapist_view_base.html" %}
{% from "core/macros.html" import init_table_magic %}

{% block client_content %}
    <h2>Přehled vyplněných testů</h2>
    {% if tests %}
        {% include "common/_test_history.html" %}
    {% else %}
        <p>Zde budou k dispozici výsledky jednotlivých testů klienta.</p>
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ init_table_magic(table_id="tests",
                        columns=[ {'type': 'moment-timestamp'}, None, None ],
                        order=[[0, 'desc' ]],
                        paging_type="full_numbers") }}
{% endblock %}