app/therapist/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email

from app.errors.form_error_msg import FormErrorMsg


class AddClientForm(FlaskForm):
    email = StringField('Email, pod kterým se klient registroval',
                        validators=[DataRequired(message=FormErrorMsg.Email.Required),
                                    Email(message=FormErrorMsg.Email.Invalid)])
    submit = SubmitField('Přidat klienta')

app/client/__init__.py
"""This module provides functionality for treated clients."""

from flask import Blueprint

bp = Blueprint('client', __name__)

from app.client import forms, routes

app/client/routes.py
from datetime import datetime, timezone
import pytz

from flask import current_app, flash, Markup, redirect, render_template, request, url_for
from flask_login import current_user

from app import common, db, limiter
from app.account.role import Role, role_required
from app.account.utils import logged_user_limiter
from app.core.utils import current_local_datetime, naive_utc_to_local_datetime, redirect_to_previous
from app.client import bp
from app.client.emails import send_alliance_accepted_email, send_break_alliance_confirmation_email, send_farewell_email
from app.client.forms import FarewellForm, ThoughtRecordForm
from app.models import Test, ThoughtRecord, User
from app.tests import graphs as test_graphs
from app.tests.cesd_r import CESD_R
from app.tests.test_selector import TestSelector
from config import Config


@bp.route('/accept-alliance/<token>')
@role_required(Role.Client)
def accept_alliance(token):
    alliance_members = User.verify_alliance_offer_token(token)
    if not alliance_members:
        flash("Požadavek neúspěšný. Pravděpodobně vypršela platnost odkazu.")
        return redirect(url_for('core.index'))

    client = alliance_members['client']
    if client != current_user:
        flash("Propojení nelze provést - použitý odkaz patří jinému uživateli.")
        return redirect(url_for('core.index'))

    therapist = alliance_members['therapist']
    if client.is_in_alliance(therapist):
        flash("Tento terapeut je s Vámi již propojen.")
        return redirect(url_for('core.index'))
    else:
        therapist.add_client(client)
        db.session.commit()
        send_alliance_accepted_email(therapist, client)
        return render_template('client/alliance_created.html', title='Terapeutická aliance vytvořena',
                               client=client, therapist=therapist)


@bp.route('/break-alliance-request/<public_id>')
@limiter.limit(Config.PREVENT_EMAIL_SPAM_VIEW_LIMIT, key_func=logged_user_limiter)
@role_required(Role.Client)
def break_alliance_request(public_id):
    therapist = User.query.filter_by(public_id=public_id).first_or_404()
    send_break_alliance_confirmation_email(current_user, therapist)
    flash("Žádost o ukončení terapeutického vztahu přijata. \
           Na Vaši emailovou adresu byl odeslán email s dalšími instrukcemi.")
    return redirect(url_for('account.edit_profile'))


@bp.route('/break-alliance/<token>/<send_message>', methods=['GET', 'POST'])
@role_required(Role.Client)
def break_alliance(token, send_message):
    alliance_members = User.verify_break_alliance_token(token)
    if not alliance_members:
        flash("Požadavek neúspěšný. Pravděpodobně vypršela platnost odkazu, \
               nebo již byl tento terapeut od Vás odpojen.")
        return redirect(url_for('core.index'))
    client = alliance_members['client']
    if client != current_user:
        flash("Zrušení nelze provést - použitý odkaz patří jinému uživateli.")
        return redirect(url_for('core.index'))
    therapist = alliance_members['therapist']

    if not client.is_in_alliance(therapist):
        flash("Tento teraput již od Vás byl odpojen. \
               Pokud je pro Vás toto překvapením, zkontrolujte svou emailovou schránku. \
               Je možné, že Váš terapeut zrušil propojení před Vámi.")
        return redirect(url_for('core.index'))

    if send_message == 'False':
        current_user.break_alliance(therapist)
        db.session.commit()
        send_farewell_email(therapist, client, message=None)
        return render_template('client/alliance_end.html', title='Zrušení propojení',
                               client=client, therapist=therapist)
    else:
        form = FarewellForm()
        if form.validate_on_submit():
            if client.is_in_alliance(therapist):
                current_user.break_alliance(therapist)
                db.session.commit()
                send_farewell_email(therapist, client, form.message.data)
                flash("Zpráva odeslána. Děkujeme za zpětnou vazbu.")
                return render_template('client/alliance_end.html', title='Zrušení propojení',
                                       client=client, therapist=therapist)
            else:
                flash("Tento teraput již od Vás byl odpojen. Zprávu nelze odeslat. \
                       Pokud je pro Vás toto překvapením, zkontrolujte svou emailovou schránku. \
                       Je možné, že Váš terapeut zrušil propojení před Vámi.")
                flash(Markup(f'Zde je kopie Vaší zprávy, pokud byste ji chtěl/-a poslat emailem: <br> \
                               """<br>{form.message.data}<br>"""'))
                return redirect(url_for('core.index'))
        return render_template('client/alliance_farewell.html', title='Zrušení propojení',
                               client=client, therapist=therapist, token=token, form=form)


@bp.route('/client-manual')
@role_required(Role.Client)
def manual():
    return render_template('client/manual.html', title='Návod k užívání aplikace')


@bp.route('/thought-record-overview')
@role_required(Role.Client)
def thought_record_overview():
    thought_records = current_user.thought_records.order_by(ThoughtRecord.timestamp.desc()) \
        .paginate(1, current_app.config['THOUGHT_RECORDS_PER_PAGE_OVERVIEW'], False)
    return render_template('client/thought_record_overview.html', title='Záznamy myšlenek',
                           thought_records=thought_records.items)


@bp.route('/new-thought-record', methods=['GET', 'POST'])
@limiter.limit(Config.UNCOMMON_POST_REQUEST_VIEWS_LIMIT, key_func=logged_user_limiter, methods=['POST'])
@role_required(Role.Client)
def new_thought_record():
    form = ThoughtRecordForm()
    if form.validate_on_submit():
        date = form.date.data
        time = form.time.data
        local_tz = pytz.timezone(current_app.config['DEFAULT_TIMEZONE'])
        timestamp = local_tz.localize(datetime.combine(date, time)).astimezone(timezone.utc)
        thought_record = ThoughtRecord(timestamp=timestamp,
                                       situation=form.situation.data,
                                       automatic_thoughts=form.automatic_thoughts.data,
                                       emotions=form.emotions.data,
                                       alternative_thoughts=form.alternative_thoughts.data,
                                       result=form.result.data,
                                       user_id=current_user.id)
        db.session.add(thought_record)
        db.session.commit()
        flash("Myšlenka zapsána.")
        return redirect(url_for('client.thought_record_overview'))
    elif request.method == 'GET':
        current_datetime = current_local_datetime()
        form.time.data = current_datetime
        form.date.data = current_datetime
    return render_template('client/new_thought_record.html', title='Nový záznam', form=form)


@bp.route('/edit-thought-record/<id>', methods=['GET', 'POST'])
@limiter.limit(Config.UNCOMMON_POST_REQUEST_VIEWS_LIMIT, key_func=logged_user_limiter, methods=['POST'])
@role_required(Role.Client)
def edit_thought_record(id):
    thought_record = ThoughtRecord.query.filter_by(user_id=current_user.id, id=id).first_or_404()
    form = ThoughtRecordForm()
    if form.validate_on_submit():
        date = form.date.data
        time = form.time.data
        local_tz = pytz.timezone(current_app.config['DEFAULT_TIMEZONE'])
        timestamp = local_tz.localize(datetime.combine(date, time)).astimezone(timezone.utc)
        thought_record.timestamp = timestamp
        thought_record.situation = form.situation.data
        thought_record.automatic_thoughts = form.automatic_thoughts.data
        thought_record.emotions = form.emotions.data
        thought_record.alternative_thoughts = form.alternative_thoughts.data
        thought_record.result = form.result.data
        db.session.commit()
        flash("Úspěšně upraveno.")
        return redirect_to_previous()
    elif request.method == 'GET':
        timestamp = naive_utc_to_local_datetime(thought_record.timestamp)
        form.time.data = timestamp
        form.date.data = timestamp
        form.situation.data = thought_record.situation
        form.automatic_thoughts.data = thought_record.automatic_thoughts
        form.emotions.data = thought_record.emotions
        form.alternative_thoughts.data = thought_record.alternative_thoughts
        form.result.data = thought_record.result
    return render_template('client/new_thought_record.html', title='Upravit záznam', form=form)


@bp.route('/delete-thought-record/<id>')
@limiter.limit(Config.UNCOMMON_POST_REQUEST_VIEWS_LIMIT, key_func=logged_user_limiter)
@role_required(Role.Client)
def delete_thought_record(id):
    thought_record = ThoughtRecord.query.filter_by(user_id=current_user.id, id=id).first_or_404()
    db.session.delete(thought_record)
    db.session.commit()
    flash("Záznam úspěšně smazán.")
    return redirect_to_previous()


@bp.route('/thought-record-browse/')
@role_required(Role.Client)
def thought_record_browse():
    client = current_user
    return common.routes.thought_record_browse(client, 'client.thought_record_browse')


@bp.route('/test-overview/')
@role_required(Role.Client)
def test_overview():
    tests = current_user.tests.order_by(Test.timestamp.desc()).all()
    graphs = [test_graphs.line(CESD_R.client_label, tests)] if tests else None
    return render_template('client/test_overview.html', title='Dotazníky', tests=tests,
                           graphs=graphs)


@bp.route('/take-test/<test_id>', methods=['GET', 'POST'])
@limiter.limit(Config.UNCOMMON_POST_REQUEST_VIEWS_LIMIT, key_func=logged_user_limiter, methods=['POST'])
@role_required(Role.Client)
def take_test(test_id):
    test = TestSelector.select_test(test_id)
    form = test.form()
    if form.validate_on_submit():
        timestamp = datetime.utcnow()
        item_scores = {item_id: score for item_id, score in form.data.items()

app/therapist/__init__.py
"""This module provides functionality for therapists."""

from flask import Blueprint

bp = Blueprint('therapist', __name__)

from app.therapist import forms, routes

app/therapist/routes.py
from flask import flash, Markup, redirect, render_template, url_for
from flask_login import current_user

from app import common, db, limiter
from app.account.role import Role, role_required
from app.account.utils import logged_user_limiter
from app.therapist import bp
from app.therapist.emails import send_alliance_end_email, send_alliance_offer_email
from app.therapist.forms import AddClientForm
from app.models import Test, ThoughtRecord, User
from app.tests.cesd_r import CESD_R
from app.tests import graphs as test_graphs
from config import Config


@bp.route('client/<public_id>/thought-record-browse/')
@role_required(Role.Therapist)
def thought_record_browse(public_id):
    client = User.query.filter_by(public_id=public_id).first_or_404()
    return common.routes.thought_record_browse(client, 'therapist.thought_record_browse',
                                               public_id=public_id)


@bp.route('/list-of-clients')
@role_required(Role.Therapist)
def list_of_clients():  # TODO: cells with links to clients' lists of tests and TRecords could show timestamp of last test/TRecord written
    return render_template('therapist/list_of_clients.html', user=current_user, clients=current_user.clients.all())


@bp.route('/add-client', methods=['GET', 'POST'])
@limiter.limit(Config.ADD_CLIENT_VIEW_LIMIT, key_func=logged_user_limiter, methods=['POST'])
@role_required(Role.Therapist)
def add_client():
    form = AddClientForm()
    if form.validate_on_submit():
        form_email = form.email.data.lower()
        if current_user.email == form_email:
            flash("Nelze sledovat sebe sama.")
            return redirect(url_for('therapist.add_client'))
        client = User.query.filter(User.email == form_email) \
                           .filter(User.role == Role.Client).first()
        if client:
            if client.is_in_alliance(current_user):
                flash(Markup(f"Klient na emailu {form_email} je s Vámi již propojen. <br><br> \
                               Klienta lze nalézt vyhledáním dle emailu v tabulce níže nebo na \
                               <a href='{url_for('therapist.client_overview', public_id=client.public_id)}'> \
                               tomto odkazu</a>."))
                return redirect(url_for('therapist.list_of_clients'))
            send_alliance_offer_email(client, current_user)
        flash(f"Zpracováváme Vaši žádost o propojení s klientem na emailu: {form_email}. \
                Nachází-li se v naší databázi, bude mu odeslána pozvánka. O jejím přijetí budete notifikováni \
                emailem.")
        return redirect(url_for('therapist.list_of_clients'))
    return render_template('therapist/add_client.html', user=current_user, form=form)


@bp.route('/remove-client/<public_id>')
@role_required(Role.Therapist)
def remove_client(public_id):
    client = User.query.filter_by(public_id=public_id).first_or_404()
    if current_user.is_in_alliance(client):
        current_user.break_alliance(client)
        db.session.commit()
        send_alliance_end_email(client, current_user)
        flash(f"Uživatel {client.email} odebrán.")
    return redirect(url_for('therapist.list_of_clients'))


@bp.route('/client/<public_id>')
@role_required(Role.Therapist)
def client_overview(public_id):
    client = User.query.filter_by(public_id=public_id).first_or_404()
    tests = client.tests.filter_by(test=CESD_R.label).order_by(Test.timestamp.desc()).all()
    thought_records = client.thought_records.order_by(ThoughtRecord.timestamp.desc()).all()
    graphs = [test_graphs.line(CESD_R.label, tests)] if tests else None
    return render_template('therapist/client_overview.html', client=client, thought_records=thought_records,
                           tests=tests, graphs=graphs)


@bp.route('/client/<public_id>/test-browse')
@role_required(Role.Therapist)
def test_browse(public_id):
    client = User.query.filter_by(public_id=public_id).first_or_404()
    tests = client.tests.order_by(Test.timestamp.desc()).all()
    return render_template('therapist/test_browse.html', client=client, tests=tests)


@bp.route('/manual')
@role_required(Role.Therapist)
def manual():
    return render_template('therapist/manual.html', title='Návod k užívání PAT')

app/templates/client/alliance_farewell.html
{% extends "core/base.html" %}
{% from "bootstrap/form.html" import render_form as render_wtform %}

{% block app_content %}
    <h1>Ukončení propojení s terapeutem {{ therapist.username }}</h1>
    <p>
        Vaše propojení s terapeutem {{ therapist.username }} bude ukončeno odesláním zprávy,
        kterou můžete sepsat ve formuláři pod tímto odstavcem.
    </p>
    <p>
        Pokud si budete přát ukončit propojení bez odeslání zprávy, můžete tak učinit kliknutím
        na odkaz pod formulářem.
    </p>
    <p>
        Pokud jste si situaci rozmyslel/-a a již nechcete propojení zrušit, stačí opustit
        tuto stránku například <a href="{{ url_for('core.index') }}">kliknutím zde</a>.
    </p>
    {{ render_wtform(form) }}
    <hr>
    <a href="{{ url_for('client.break_alliance', token=token, send_message=False) }}">
        Ukončit vztah bez odeslání zprávy
    </a>
{% endblock %}

app/templates/client/manual.html
{% extends "core/base.html" %}

{% block app_content %}
<h1>
    Návod k užívání PAT
</h1>
<ul class="nav nav-tabs" id="infoTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="thought_records-tab" data-toggle="tab" href="#thought_records"
           role="tab" aria-controls="thought records" aria-selected="true">
            Záznamy automatických myšlenek
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tests-tab" data-toggle="tab" href="#tests"
           role="tab" aria-controls="tests" aria-selected="false">
            Dotazníky
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="therapeutic_alliance-tab" data-toggle="tab" href="#therapeutic_alliance"
           role="tab" aria-controls="therapeutic alliance" aria-selected="false">
            Terapeutická aliance
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="edit_profile-tab" data-toggle="tab" href="#edit_profile"
           role="tab" aria-controls="edit_profile" aria-selected="false">
            Úprava účtu
        </a>
    </li>
</ul>
<div class="tab-content" id="infoTabContent">
    <div class="tab-pane fade show active responsive-tab" id="thought_records" role="tabpanel" aria-labelledby="thought_records-tab">
        <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="thought_records">
                <a href="#collapse-thought_records" data-toggle="collapse">
                    <h5 class="mb-0">
                        Záznamy automatických myšlenek
                    </h5>
                </a>
            </div>
        <div id="collapse-thought_records" class="collapse" role="tabpanel">
            <h3>
                Umístění
            </h3>
            <p>
                Všechny zde uvedené úkony lze provést v sekci
                <a href="{{ url_for('client.thought_record_overview') }}">Záznamy myšlenek.</a>
            </p>
            <h3>
                Vytvoření nového záznamu
            </h3>
            <p>
                Nový záznam lze vytvořit kliknutím na tlačítko 'Nový záznam'. Všechna pole jsou pro Vaše pohodlí
                volitelná, s výjimkou času. Je to proto, abyste mohl/-a uložit nedokončený záznam a později ho
                upravit. Záznamy doporučujeme dokončit, případně postup konzultovat s terapeutem.
            <p>
                Prázdný záznam uložit nelze.
            </p>
            <h3>
                Úprava a smazání záznamu
            </h3>
            <p>
                Záznam můžete kdykoliv upravit, a to jak v
                <a href="{{ url_for('client.thought_record_overview') }}">Nedávných záznamech</a>, tak v
                <a href="{{ url_for('client.thought_record_browse') }}">Přehledu záznamů,</a> najetím myši
                na daný záznam – v pravém okraji záznamu se pak objeví dvě tlačítka: horní pro úpravu záznamu,
                dolní pro smazání. Na zařízeních s dotykovým ovládáním se tlačítka zobrazí po klepnutí na daný záznam.
            </p>
            <h3>
                Vyhledávání a řazení záznamů
            </h3>
            <p>
                V <a href="{{ url_for('client.thought_record_browse') }}">Přehledu záznamů myšlenek</a> lze vyhledávat
                užitím pole 'Vyhledat' v pravém horním rohu přehledu. Vyhledání není potřeba potvrzovat žádnou klávesou,
                probíhá v reálném čase během psaní. Vyhledávání prochází všechna pole záznamu myšlenky, lze vyhledat
                i konkrétní datum nebo čas. Čas nebo datum je nutno zadat ve stejném formátu jako je v jednotlivých záznamech.
            </p>
            <p>
                Záznamy je možno řadit podle data poklepáním na šipky vedle nadpisu 'Čas'. Výchozí řazení je sestupné
                podle času – nejvýše jsou nové myšlenky.
            </p>
            <p>
                Záznamy lze řadit i dle ostatních polí – toho lze využít pro nalezení nedokončených záznamů. Pokud
                například kliknete na nadpis 'Výsledek', aby se záznamy seřadily vzestupně podle tohoto pole
                (napravo od nadpisu 'Výsledek' bude začerněna šipka směřujíc vzhůru), seřadí se na vrcholu
                přehledu všechny záznamy, jež nemají vyplněno pole 'Výsledek'.
            </p>
        </div>
    </div>
    <div class="tab-pane fade responsive-tab" id="tests" role="tabpanel" aria-labelledby="tests-tab">
        <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="tests">
                <a href="#collapse-tests" data-toggle="collapse">
                    <h5 class="mb-0">
                        Dotazníky
                    </h5>
                </a>
            </div>
        <div id="collapse-tests" class="collapse" role="tabpanel">
            <h3>
                Umístění
            </h3>
            <p>
                Všechny zde uvedené úkony lze provést v sekci
                <a href="{{ url_for('client.test_overview') }}">Dotazníky.</a>
            </p>
            <h3>
                Vyplnění nového dotazníku
            </h3>
            <p>
                Dotazník lze vyplnit kliknutím na tlačítko 'Nový dotazník'. Následně postupujte podle instrukcí dotazníku.
                Po odeslání dotazníku bude provedeno základní vyhodnocení. Na základě výsledků však prosíme
                nikdy nedělejte závěry a konzultujte je nejdříve s Vaším terapeutem.
            </p>
            <h3>
                Smazání výsledku dotazníku
            </h3>
            <p>
                Pokud máte pocit, že jste se v dotazníku překlikl/-a nebo došlo k nějaké chybě, můžete daný dotazníků
                smazat kliknutím na tlačítko 'Smazat test' v seznamu testů.
            </p>
            <p>
                Mazání výsledků dotazníků obecně není doporučováno. Každý výsledek může být nějak přínosný
                a doporučujeme každé případné mazání nejprve konzultovat s terapeutem – může se např. stát, že Váš
                pocit potřeby smazat výsledek dotazníku nepochází z Vás, ale z nějakého projevu depresivního onemocnění.
            </p>
            <h3>
                Graf vývoje
            </h3>
            <p>
                Tento graf umožňuje hrubý náhled, jak se Váš stav mohl měnit v čase. Tento graf je jen orientační a
                nelze na základě něj dělat konkrétní závěry. Interpretaci nejdříve konzultujte s Vaším terapeutem.
            </p>
            <p>
                V grafu je možné libovolné úseky přiblížit/oddálit kolečkem myši. Pro návrat do výchozího zobrazení
                lze dvakrát poklepat na graf nebo kliknout na malou ikonku domečku v pravém horním rohu grafu.
            </p>
            <h3>
                Jak často dotazníky vyplňovat
            </h3>
            <p>
                Frekvenci vyplňování dotazníků konzultujte s Vaším terapeutem. Doporučená doba se může lišit
                podle stavu a specifik konkrétního depresivního onemocnění.
            </p>
        </div>
    </div>
    <div class="tab-pane fade responsive-tab" id="therapeutic_alliance" role="tabpanel" aria-labelledby="therapeutic_alliance-tab">
        <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="therapeutic_alliance">
                <a href="#collapse-therapeutic_alliance" data-toggle="collapse">
                    <h5 class="mb-0">
                        Terapeutická aliance
                    </h5>
                </a>
            </div>
        <div id="collapse-therapeutic_alliance" class="collapse" role="tabpanel">
            <h3>
                Terapeutický vztah
            </h3>
            <p>
                Terapeutický vztah zde označuje propojení účtu klienta s účtem terapeuta.
                Je možno navázat vztah s více terapeuty současně – u některých případů depresivního onemocnění je
                běžná spolupráce psychiatra s psychoterapeutem. V takovém případě pak můžete svůj účet propojit
                s oběma.
            </p>
            <h3>
                Jak vznikne a co znamená
            </h3>
            <p>
                Na jednom z terapeutických sezení Vám Váš terapeut pravděpodobně PAT představil a pomohl vytvořit
                účet. Propojení vznikne tak, že terapeut nejprve v PAT podá žádost o projení s Vaším účtem.
                Vám následně přijde na email, jež jste použil/-a při registraci, zpráva o této žádosti a potvrzovacím
                odkazem. Použitím tohoto odkazu se Vaše účty propojí.
            </p>
            <p>
                Terapeut tak bude mít po dobu Vašeho propojení přístup k Vašim terapeutickým datům – vyplněným
                záznamům myšlenek, výsledkům testů a grafu vývoje. Po dobu propojení uvidí v PAT i Vaši emailovou
                adresu.
            </p>
            <h3>
                Ukončení vztahu
            </h3>
            <p>
                Terapeutický vztah můžete ukončit Vy i Váš terapeut. Pokud byste si přál/-a vztah ukončit,
                lze tak učinit v sekci <a href="{{ url_for('account.edit_profile') }}">Upravit profil.</a>
            </p>
            <p>
                Pokud by naopak terapeut ukončil propojení s Vámi, bude Vám odesláno upozornění na email.
            </p>
            <p>
                Dále vztah může zaniknout pokud byste Vy nebo Váš terapeut dokončil žádost o smazání účtu.
                V takovém případě bude propojení ukončeno a protistrana bude o tomto stavu upozorněna.
            </p>
        </div>
    </div>
    <div class="tab-pane fade responsive-tab" id="edit_profile" role="tabpanel" aria-labelledby="edit_profile-tab">
        <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="edit_profile">
                <a href="#collapse-edit_profile" data-toggle="collapse">
                    <h5 class="mb-0">
                        Úprava účtu
                    </h5>
                </a>
            </div>
        <div id="collapse-edit_profile" class="collapse" role="tabpanel">
            <h3>
                Umístění
            </h3>
            <p>
                Všechny zde uvedené úkony lze provést v sekci
                <a href="{{ url_for('account.edit_profile') }}">Upravit profil.</a>
            </p>
            <h3>
                Uživatelské jméno
            </h3>
            <p>
                Své uživatelské jméno můžete kdykoliv změnit.
                Pod tímto jménem Vás vidí terapeuté, se kterými jste v terapeutickém vztahu.
            </p>
            <h3>
                Změna hesla
            </h3>
            <p>
                Pro změnu hesla je z bezpečnostních důvodů nutné mít přístup na email, s nímž jste se v PAT
                registroval/-a. Po odeslání žádosti o změnu v sekci
                <a href="{{ url_for('account.edit_profile') }}">Upravit profil</a>
                Vám bude na tento email odeslán potvrzovací odkaz. Ten Vás přesměruje na formulář k vytvoření
                nového hesla.
            </p>
            <h3>
                Seznam propojených terapeutů
            </h3>
            <p>
                Zde je k dispozici seznam terapeutů se kterými jste v PAT vstoupil/-a do terapeutického vztahu.
                Prostřednictvím tohoto seznamu je možno propojení s konkrétním terapeutem ukončit.
            </p>
            <h3>
                Smazání účtu
            </h3>
            <p>
                Smazání účtu je nevratná záležitost s okamžitou platností. Po odeslání žádosti Vám na email uvedený
                při registraci přijde potvrzovací odkaz. Použitím tohoto odkazu bude Váš účet a všechna Vaše data
                s ním spojená trvale smazána.
            </p>
            <p>
                Pokud byste si smazání účtu po odeslání žádosti rozmyslel/-a je tak možno pouze před použitím
                potvrzovacího odkazu. V takovém případě doporučujeme email s odkazem z bezpečnostních důvodů smazat.
                Po užití odkazu již obnova účtu není možná.
            </p>
        </div>
    </div>
</div>
{% endblock %}

app/templates/client/thought_record_overview.html
{% extends "core/base.html" %}
{% from "core/macros.html" import init_table_magic %}

{% block app_content %}
    <h1>Záznamy myšlenek</h1>
    <a class="btn btn-primary" href="{{ url_for('client.new_thought_record') }}" role="button">
         Nový záznam
    </a>
    <h2 class="mt-3">Nedávné záznamy</h2>
    {% if thought_records %}
        <a href="{{ url_for('client.thought_record_browse') }}">Přejít na zobrazení všech záznamů</a>
        {% include "common/_thought_record_history.html" %}
    {% else %}
        <p>Zde budou k dispozici vyplněné záznamy myšlenek.</p>
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ init_table_magic(table_id="thought_records",
                        columns=[ {'type': 'moment-timestamp'}, None, None, None, None, None, {'orderable': false} ],
                        order=[[0, 'desc' ]],
                        info=False,
                        length_change=False,
                        ordering=False,
                        paging=False,
                        searching=False) }}
{% endblock %}