app/core/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email, Length, Optional

from config import FieldLengths
from app.errors.form_error_msg import FormErrorMsg


class ContactUserSupportForm(FlaskForm):
    email = StringField('Email pro obdržení odpovědi (nepovinný)',
                        validators=[Email(message=FormErrorMsg.Email.Invalid),
                                    Optional()])
    subject = StringField('Předmět zprávy', validators=[Length(max=FieldLengths.Message.Max.UserSupportMailSubject,
                                                               message=FormErrorMsg.UserSupportMailSubject.MaxLength)])
    message = TextAreaField('Zpráva',
                            validators=[DataRequired(message=FormErrorMsg.UserSupportMail.Required),
                                        Length(max=FieldLengths.Message.Max.UserSupportMail,
                                               message=FormErrorMsg.UserSupportMail.MaxLength)])
    submit = SubmitField('Odeslat zprávu')

app/core/__init__.py
"""This module covers the base of the app and general functionality that is shared between multiple modules."""

from flask import Blueprint

bp = Blueprint('core', __name__)

from app.core import routes, utils

app/core/routes.py
from flask import flash, redirect, render_template, url_for

from app import limiter
from app.account.utils import common_endpoints_limiter
from app.core import bp
from app.core.emails import send_user_support_email
from app.core.forms import ContactUserSupportForm
from config import Config


@bp.route('/about')
def about():
    return render_template('core/about.html', title='O PAT')


@bp.route('/client-introduction')
def client_intro():
    return render_template('core/client_intro.html', title='Úvod pro klienty')


@bp.route('/therapist-introduction')
def therapist_intro():
    return render_template('core/therapist_intro.html', title='Úvod pro terapeuty')


@bp.route('/contact-user-support', methods=['GET', 'POST'])
@limiter.limit(Config.CONTACT_USER_SUPPORT_VIEW_LIMIT, key_func=common_endpoints_limiter, methods=['POST'])
def contact_user_support():
    form = ContactUserSupportForm()
    if form.validate_on_submit():
        send_user_support_email(message=form.message.data,
                                user_subject=form.subject.data,
                                reply_email=form.email.data)
        flash("Zpráva odeslána.")
        return redirect(url_for('core.index'))
    return render_template('core/contact_user_support.html', title='Kontaktování uživatelské podpory',
                           form=form)


@bp.route('/finding-help')
def finding_help():
    return render_template('core/finding_help.html', title='Vyhledání pomoci')


@bp.route('/')
@bp.route('/index')
def index():
    return render_template('core/index.html', title='Úvodní stránka')


@bp.route('/licence')
def licence():
    return render_template('core/licence.html', title='Licence')


@bp.route('/privacy')
def privacy():
    return render_template('core/privacy.html', title='Soukromí')


@bp.route('/psychology-information')
def psychoeducational_materials():
    return render_template('core/psychoeducational_materials.html', title='Informace')


@bp.route('/psychological-background')
def psychological_background():
    return render_template('core/psychological_background.html', title='Informace pro terapeuty')

app/templates/core/_footer.html
{% from 'core/macros.html' import highlight_active %}
<footer class="footer mt-auto py-3">
    <div class="container text-right">
        <small>
            <a class="{{ highlight_active('core.about') }}" href="{{ url_for('core.about') }}">
                O aplikaci
            </a>
            <a class="{{ highlight_active('core.privacy') }}" href="{{ url_for('core.privacy') }}">
                Soukromí
            </a>
            <a class="{{ highlight_active('core.licence') }}" href="{{ url_for('core.licence') }}">
                Licence
            </a>
            <a class="{{ highlight_active('core.contact_user_support') }}"
               href="{{ url_for('core.contact_user_support') }}">
                Kontakt
            </a>
        </small>
        <br>
        <small class="text-muted">&copy;PAT, 2020</small>
    </div>
</footer>

app/templates/core/_index_therapist.html
<h1>
    Úvodní stránka
</h1>
<h2>
    Vítejte v PAT
</h2>
<p>
    PAT má k dispozici několik modulů, z nichž si můžete vybrat níže:
</p>
<div class="row card-deck mb-2">
    <div class="col-md">
        <div class="card text-center">
            <a href="{{ url_for('therapist.list_of_clients') }}" class="btn btn-outline-primary">
                <div class="card-body">
                    <h3>
                        Seznam klientů
                    </h3>
                    <p class="card-text">
                        Přehled jednotlivých klientů a jejich správa
                    </p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md">
        <div class="card text-center">
            <a href="{{ url_for('therapist.add_client') }}" class="btn btn-outline-primary">
                <div class="card-body">
                    <h3>
                        Přidat klienta
                    </h3>
                    <p class="card-text">
                        Odeslání žádosti o propojení
                    </p>
                </div>
            </a>
        </div>
    </div>
</div>

<div class="row card-deck">
    <div class="col-md">
        <div class="card text-center">
            <a href="{{ url_for('core.psychological_background') }}" class="btn btn-outline-primary">
                <div class="card-body">
                    <h3>
                         Psychologické pozadí PAT
                    </h3>
                    <p class="card-text">
                        Doplňující informace k užitým materiálům a principu
                    </p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md">
        <div class="card text-center">
            <a href="{{ url_for('therapist.manual') }}" class="btn btn-outline-primary">
                <div class="card-body">
                    <h3>
                        Jak PAT použít
                    </h3>
                    <p class="card-text">
                        Návod a vysvětlení jednotlivých funkcí PAT
                    </p>
                </div>
            </a>
        </div>
    </div>
</div>

app/templates/core/_pagination_links.html
<nav aria-label="Aktuální stránka">
    <div class="pagination row">
        <div class="col-6 text-left">
            <div class="page-item btn btn-outline">
                <a class="page-link btn previous{% if not prev_url %} disabled{% endif %}" href="{{ prev_url or '#' }}"
                   aria-label="Předchozí">
                    <span aria-hidden="true">
                        <svg class="bi bi-chevron-left" width="1em" height="1em"
                             viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                  d="M13.354 3.646a.5.5 0 010 .708L7.707 10l5.647 5.646a.5.5 0 01-.708.708l-6-6a.5.5 0 010-.708l6-6a.5.5 0 01.708 0z"
                                  clip-rule="evenodd"/>
                        </svg>
                    </span>Předchozí
                </a>
            </div>
        </div>
        <div class="col-6 text-right">
            <div class="page-item btn btn-outline">
                <a class="page-link btn next{% if not next_url %} disabled{% endif %}" href="{{ next_url or '#' }}"
                   aria-label="Další">
                    Další <span aria-hidden="true">
                            <svg class="bi bi-chevron-right" width="1em" height="1em"
                                 viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M6.646 3.646a.5.5 0 01.708 0l6 6a.5.5 0 010 .708l-6 6a.5.5 0 01-.708-.708L12.293 10 6.646 4.354a.5.5 0 010-.708z"
                                      clip-rule="evenodd"/>
                            </svg>
                    </span>
                </a>
            </div>
        </div>
    </div>
</nav>

app/templates/core/about.html
{% extends "core/base.html" %}

{% block app_content %}
    <h2>
        O PAT
    </h2>
    <h3>
        Vznik a budoucí směřování
    </h3>
    <p>
        PAT vznikla jako bakalářská práce na Univerzitě Palackého. Jejím autorem je bývalý psycholog,
        který zběhl k programování a tvorbě počítačových aplikací.
    </p>
    <p>
        PAT momentálně čeká na svou obhajobu v roce 2020. Po obhajobě je v plánu s PAT pokračovat jako
        s volnočasovým projektem - dokud bude pomáhat alespoň jednomu člověku, budu jako autor spokojený.
    </p>
    <h3>
        Poděkování
    </h3>
    <p>
        Velké poděkování patří všem stranám, bez kterých by PAT nevznikla:
    </p>
    <ul>
        <li>všem psychoterapeutům, kteří pomáhali/pomáhají s vývojem</li>
        <li>všem, kdo se podíleli/podílejí na testování PAT</li>
        <li>komunitě Pythonu a Flasku, na jejichž softwarovém základu PAT stojí</li>
        <li><a href="https://getbootstrap.com/">Bootstrap</a></li>
        <li><a href="https://github.com/feathericons/feather">Feathericons</a></li>
        <li><a href="https://github.com/primer/octicons">Octicons</a></li>
    </ul>
{% endblock %}

app/templates/core/client_intro.html
{% extends "core/base.html" %}

{% block app_content %}
<h1>
    Úvod pro klienty
</h1>
<div class="row">
    <div class="col-md">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
                Nejsem zde na doporučení psychoterapeuta
            </h5>
            <p>
                Využijte našich informačních materiálů dle libosti, ale chtěli bychom
                varovat před užíváním terapeutického obsahu pro přihlášené uživatele -
                PAT není určena pro samoléčbu a podobně jako některé léky, její užívání
                bez odborného dohledu může Váš stav spíše zhoršit nežli zlepšit.
            </p>
            <p>
                Chcete-li se dozvědět více o počítačem asistované terapii, o depresivním onemocnění
                nebo hledáte-li přímou pomoc s psychickými obtížemi, můžete začít například zde:
            </p>
            <div class="row justify-content-center">
                <a href="{{ url_for('core.psychoeducational_materials') }}" class="btn btn-secondary mx-auto">
                    Edukativní informace
                </a>
                <a href="{{ url_for('core.finding_help') }}" class="btn btn-primary mx-auto">
                    Odkazy na pomoc
                </a>
            </div>
          </div>
        </div>
    </div>
    <div class="col-md">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
                Přišel/-a jsem na doporučení svého psychoterapeuta
            </h5>
            <p>
                Pokud s Vámi psychoterapeut užití PAT konzultoval, můžete pokračovat rovnou
                k registraci.
            </p>
            <div class="row justify-content-center">
                <a href="{{ url_for('account.register_client') }}" class="btn btn-primary">
                    Registrovat se
                </a>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/core/contact_user_support.html
{% extends "core/base.html" %}
{% from "bootstrap/form.html" import render_form as render_wtform %}

{% block app_content %}
    <h1>Kontaktování uživatelské podpory</h1>
    <p>
        V případě, že jste narazil/-a na nějaký problém během užívání aplikace,
        nebo chcete podat zpětnou vazbu, můžete využít tento formulář.
    </p>
    <p>
        Tento formulář neslouží k vyhledávání/poskytování terapeutické pomoci.
        Pro tyto účely prosíme použijte odkazy v sekci
        <a href="{{ url_for('core.finding_help') }}">Vyhledání pomoci</a>.
    </p>
    <div class="row">
        <div class="col-md-4">
            {{ render_wtform(form) }}
        </div>
    </div>
{% endblock %}

app/templates/core/finding_help.html
{% extends "core/base.html" %}
{% from "core/macros.html" import init_table_magic %}

{% block app_content %}
    <h1>Vyhledání pomoci</h1>
    <p>
        Pro vyhledání terapeuta můžeme doporučit portál <a href="https://www.znamylekar.cz/">Známý lékař</a>. Můžete zde
        vyfiltrovat psychoterapeuta podle místa ordinace a referencí ostatních klientů.
    </p>
    <p>
        Hledáte-li akutní pomoc, nebo pokud máte pocit, že psychoterapeut pro Vás momentálně není nejvhodnější
        volbou, můžeme dále doporučit podrobný seznam dalších forem pomoci od portálu
        <a href="https://nevypustdusi.cz/kde-hledat-pomoc/">Nevypusť duši</a>.
    </p>
{% endblock %}

app/templates/core/licence.html
{% extends "core/base.html" %}

{% block app_content %}
    <h1>
        Licence
    </h1>
    <p>
        PAT je licencována pod licencí Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
        (CC BY-NC-SA 4.0).
    </p>
    <p>
        Její zkrácené i plné znění jsou k dispozici
        <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.cs" >zde.</a>
    </p>
{% endblock %}

app/templates/core/privacy.html
{% extends "core/base.html" %}

{% block app_content %}
    <h1>
        Soukromí
    </h1>
    <p>
        Žádná z Vašich dat nejsou přeposílána ani přeprodávána třetím stranám. Během vývoje PAT byl kladen důraz na to,
        aby nic podobného nedělaly ani použité nástroje.
    </p>
    <p>
        Na bezpečnost a soukromí Vašich dat je kladen maximální důraz. Data jsou uložena v databázovém serveru PAT,
        se kterým je manipulováno jen za účelem vývoje a oprav chyb. Data jsou sdílena pouze s terapeuty/klienty,
        jimž toto dovolíte vstupem do terapeutického vztahu. Toto rozhodnutí zároveň můžete kdykoliv zrušit.
    </p>
    <p>
        Pokud máte podezření, že některé z použitých softwarových nástrojů sledování návštěvníků
        provozuje, kontaktujte nás prosím prostřednictvím
        <a href="{{ url_for('core.contact_user_support') }}"> tohoto formuláře.</a>
    </p>
    <h3>
        Smazání dat
    </h3>
    <p>
        Přejete-li si, je možné Vaše data z aplikace smazat. Toto můžete provést v sekci
        <a href="{{ url_for('account.edit_profile') }}">Upravit profil</a>,
        po přihlášení do PAT.
    </p>
{% endblock %}

app/templates/core/psychological_background.html
{% extends "core/base.html" %}

{% block app_content %}
    <h1>
        Informace pro terapeuty
    </h1>
    <ul class="nav nav-tabs" id="infoTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="pat-tab" data-toggle="tab" href="#pat"
               role="tab" aria-controls="PAT" aria-selected="true">
                Počítačem asistovaná terapie
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="tests-tab" data-toggle="tab" href="#tests"
               role="tab" aria-controls="tests" aria-selected="false">
                Použité dotazníky
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="planned_development-tab" data-toggle="tab" href="#planned_development"
               role="tab" aria-controls="planned development" aria-selected="false">
                Plánovaná rozšíření funkcí
            </a>
        </li>
    </ul>
    <div class="tab-content" id="infoTabContent">
        <div class="tab-pane fade show active responsive-tab" id="pat" role="tabpanel" aria-labelledby="pat-tab">
            <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="PAT">
                <a href="#collapse-pat" data-toggle="collapse">
                    <h5 class="mb-0">
                        Počítačem asistovaná terapie
                    </h5>
                </a>
            </div>
            <div id="collapse-pat" class="collapse" role="tabpanel">
                <h3>
                    Princip
                </h3>
                <p>
                    Počítačem asistovaná terapie je relativně starý koncept - první aplikace vznikaly už v minulém
                    století. Její základní myšlenka je relativně jednoduchá - využití počítačového programu
                    pro usnadnění či vylepšení průběhu běžné psychoterapie.
                </p>
                <p>
                    Tyto programy mívají různou formu - např. některé fungují na principu videozáznamů, kterými se klientům
                    snaží předat nové mentální návyky na zvládání a prevenci depresivních stavů. Jiné využívají systému
                    online kurzů. Objevily se i pokusy o vytvoření terapeutického
                    <a href="https://cs.wikipedia.org/wiki/Chatbot">"chatbota"</a> (=program, který komunikuje s klientem
                    prostřednictvím chatu a snaží se poskytnout klientovi terapeutickou pomoc jako náhrada
                    za psychoterapeuta-člověka).
                </p>
                <p>
                    Programy počítačem asistované terapie se liší ještě v jedné klíčové vlastnosti - mírou, ve které
                    nahrazují či doplňují běžnou psychoterapii. Existují jak programy, které se snaží běžnou
                    terapii absolutně nahradit, tak programy, které záměrně slouží jen jako doplněk klasické psychoterapie
                    a jejich používání bez terapeutického dohledu není doporučeno.
                </p>
                <h3>
                    Úloha PAT v léčbě
                </h3>
                <p>
                    PAT je jednou z aplikací určených pro počítačem asistovanou terapii. Byla vyvinuta jako
                    doplňek psychoterapie - nesnaží se psychoterapii nahradit, jen ji vhodně doplnit, aby terapie
                    byla klientovi dostupná 24 hodin denně i mimo aktivní sezení u terapeuta. K jejímu použití stačí
                    připojení k internetu - použít se dá na počítači, tabletu i chytrém telefonu.
                </p>
                <p>
                    Vychází z principů kognitivně-behaviorální terapie a jejím cílem je terapii co nejvíce usnadnit,
                    a to jak pro klienty, tak pro terapeuty. Momentálně dostupnými funkcemi jsou tvorba a správa záznamů
                    automatických myšlenek, sledování vývoje terapie prostřednictvím CESD-R a možnost sdílení těchto
                    dat s vybraným terapeutem. Toto je v plánu dále rozšířit, více viz záložka 'Plánované rozšíření funkcí'.
                </p>
                <h4>
                    Záznamy automatických myšlenek
                </h4>
                <p>
                    Počítačové zpracování těchto záznamů usnadňuje organizaci a vyhledávání v těchto záznamech.
                    Hledání spouštěčů či vzorců v automatických myšlenkách klienta je tak snažší - např. identifikace,
                    v kterou denní dobu bývá deprese nejsilnější nebo jaké situace často spouští depresivní stavy.
                    Tyto záznamy navíc klient může sdílet v reálném čase - lze se tak snáze dopředu připravit na příští
                    sezení.
                </p>
                <p>
                    Jedním z dalších přínosů PAT je dostupnost. Klient má všechny své záznamy
                    na jednom místě a pro nový záznam stačí připojení k internetu na téměř libovolném zařízení.
                </p>
                <h4>
                    Průběžné sledování stavu
                </h4>
                <p>
                    Sledování vývoje stavu pomocí dotazníků může pomoci se sledováním, které metody jsou v terapii
                    účinné a které ne. Může tak pomoci s úpravou léčby a reflexí, jak terapie postupuje. Pod vlivem
                    depresivního onemocnění nejsou ojedinělé tendence zavrhovat pozitivní zkušenosti - mapování stavu
                    v tomto může pomoci jako pevný důkaz proti tomuto depresivnímu zkreslení.
                </p>
            </div>
        </div>
        <div class="tab-pane responsive-tab fade" id="tests" role="tabpanel" aria-labelledby="tests-tab">
            <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="tests">
                <a href="#collapse-tests" data-toggle="collapse">
                    <h5 class="mb-0">
                        Použité dotazníky
                    </h5>
                </a>
            </div>
            <div id="collapse-tests" class="collapse" role="tabpanel">
                <h3>
                    Aktuální paleta testů
                </h3>
                <p>
                    Momentálně je dostupná pouze
                    <a href="https://cesd-r.com/">Škála deprevisity centra pro epidemiologické studie (CESD-R).</a>
                    Ač z psychologického hlediska není nutně nejvhodnější pro všechny potřeby,
                    je jako jedna z mála licencovaná jako volně dostupná.
                </p>
                <p>
                    CESD-R je krátká, sebeposuzovací škála o 20 položkách, zaměřená na depresivní symptomy.
                    Momentálně vyhodnocení v PAT probíhá jen podle hrubého skóru. Je však v plánu rozšíření
                    o podrobnější vyhodnocení, které je blíže popsáno
                    na <a href="https://cesd-r.com/cesdr/">informačních stránkách CESD-R.</a>
                </p>
                <h3>
                    Plány do budoucna
                </h3>
                <h4>
                    Rozšíření o další testy
                </h4>
                <p>
                    Do budoucna je plánováno rozšíření o další psychologické testy, o jejichž podporu bude zájem a které
                    budou mít adekvátní licenční model. Momentálně je v plánu rozšíření například
                    o <a href="https://www.coresystemtrust.org.uk/instruments/core-om-information/">CORE-OM</a>, jehož autoři
                    tento test za určitých podmínek předávají k využití v online softwaru.
                </p>
                <p>
                    Víte-li o testu, který se Vám pro PAT zdá vhodný a má takový licenční model, který umožňuje
                    užití v software, dejte nám prosím vědět prostřednictvím
                    <a href="{{ url_for('core.contact_user_support') }}">tohoto formuláře.</a>
                </p>
                <h4>
                    Dobrovolný sběr psychometrických dat
                </h4>
                <p>
                    Vzhledem k softwarové podstatě PAT se přirozeně nabízí otázka jejího případného využití
                    pro sběr psychometrických dat/validizaci psychometrických metod. Aktuálně se v PAT nic
                    takového neprovádí.
                </p>
                <p>
                    Máte-li zájem o takovou spolupráci, můžete nás kontaktovat prostřednictvím
                    <a href="{{ url_for('core.contact_user_support') }}">tohoto formuláře.</a>
                    Předem upozorňujeme, že takovýto sběr bude uskutečněn jen za splnění následujících podmínek:
                </p>
                <ul>
                    <li>test je nějakým způsobem přínosný pro klienty PAT</li>
                    <li>test bude pro klienta dostupný až po schválení terapeutem s ním propojeným</li>
                    <li>
                        sdílení dat bude pro klienty dobrovolné a tzv. "opt-in" - žádná data nebudou od klientů sbírána
                        bez jejich vědomého souhlasu. Souhlasem se rozumí zakliknutí a následné potvrzení tohoto nastavení.
                    </li>
                    <li>pseudonymizace veškerých dat</li>
                </ul>
            </div>
        </div>
        <div class="tab-pane responsive-tab fade" id="planned_development" role="tabpanel" aria-labelledby="planned_development-tab">
            <div class="card-header responsive-accord" role="tab" aria-expanded="false" aria-controls="planned_development">
                <a href="#collapse-planned_development" data-toggle="collapse">
                    <h5 class="mb-0">
                        Plánovaná rozšíření funkcí
                    </h5>
                </a>
            </div>
            <div id="collapse-planned_development" class="collapse" role="tabpanel">
                <h3>
                    Co je v plánu
                </h3>
                <p>
                    Způsobů, jakým by PAT v terapii mohla dále pomáhat, je mnoho. Zde je k dispozici výčet
                    několika dalších plánovaných funkcí. Plány nejsou definitivní a mohou se měnit
                    podle zpětné vazby od uživatelů.
                </p>
                <p>
                    Napadne-li Vás funkcionalita, kterou byste v PAT ocenili, dejte nám o ní prosím vědět
                    prostřednictvím <a href="{{ url_for('core.contact_user_support') }}">kontaktního formuláře.</a>
                </p>
                <p>
                    V plánu je např.
                </p>
                <ul>
                    <li>
                        podpora dalších typických domácích úkolů
                        <ul>
                            <li>
                                plánování a sledování činností
                            </li>
                            <li>
                                zápis dobrých věcí, co klient za den udělal/staly se
                            </li>
                            <li>
                                vzpomínkové reskripce
                            </li>
                        </ul>
                    </li>
                    <li>
                        notifikace v aplikaci - možnost pro klienty notifikovat vybraného terapeuta, že
                        splnili zadaný úkol
                    </li>
                    <li>
                        chat - aktuálně plánovaný pouze mezi klientem a s ním propojeným terapeutem; pokud by se podařila
                        navrhnout vhodná platforma pro svépomocné skupiny, bylo by možné rozšířit
                    </li>
                    <li>
                        možnost psát si záznamy ze sezení a zapisovat si naučené psychoterapeutické metody a nové návyky
                    </li>
                    <li>
                        poznámky
                        <ul>
                            <li>
                                prostor pro terapeuty pro psaní poznámek ke klientům, jejich výsledkům dotazníků a domácím úkolům
                            </li>
                            <li>
                                prostor pro klienty si psát poznámky k výsledkům dotazníků a domácím úkolům
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/core/therapist_intro.html
{% extends "core/base.html" %}

{% block app_content %}
<h1>
    Úvod pro terapeuty
</h1>
<div class="row">
    <div class="col-md">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
                PAT mi byla doporučena a chtěl/-a bych se dozvědět více
            </h5>
            <p>
                Můžete začít naší informační brožurkou pro nové terapeuty.
                Dozvíte se o principech počítačem asistované terapie, směřování aplikace PAT
                a užitých nástrojích a testech.
            </p>
            <p>
                Případně se můžete rovnou registrovat a ozkoušet funkce PAT napřímo.
            </p>
            <div class="row justify-content-center">
                <a href="{{ url_for('core.psychological_background') }}" class="btn btn-secondary mx-auto">
                    Informace pro terapeuty</a>
                <a href="{{ url_for('account.register_therapist') }}" class="btn btn-primary mx-auto">
                    Registrovat se</a>
            </div>
          </div>
        </div>
    </div>
    <div class="col-md">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
                Jsem již s PAT seznámen/-a a chtěl/-a bych ji začít využívat
            </h5>
            <p>
                Začněte s registrací zde:
            </p>
            <div class="row justify-content-center">
                <a href="{{ url_for('account.register_therapist') }}" class="btn btn-primary mx-auto">
                    Registrovat se</a>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}